// Reads a raw Figma design-tokens export and generates CSS custom
// properties from it.
//
// Re-run this any time design-tokens/primitives.json is replaced with a
// fresh export from Figma — don't hand-edit src/styles/tokens.css.
//
// Usage: npm run tokens

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const INPUT_PATH = join(__dirname, '../design-tokens/primitives.json')
const OUTPUT_PATH = join(__dirname, '../src/styles/tokens.css')

const warnings = []

function sanitize(key) {
  return key
    .toLowerCase()
    .replace(/%/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function hexToRgb(hex) {
  const value = hex.replace('#', '')
  return [
    parseInt(value.substring(0, 2), 16),
    parseInt(value.substring(2, 4), 16),
    parseInt(value.substring(4, 6), 16),
  ]
}

function colorValue({ hex, alpha }) {
  if (alpha === 1) return hex
  const [r, g, b] = hexToRgb(hex)
  const cleanAlpha = Math.round(alpha * 100) / 100
  return `rgba(${r}, ${g}, ${b}, ${cleanAlpha})`
}

// Dispatches on the token's own $type rather than which top-level
// category it happens to be nested under. This is what catches tokens
// that ended up in the wrong group in Figma (a "number" token nested
// inside "color", for example) instead of silently mis-rendering them.
function buildLine(key, token, topCategory, path) {
  if (token.$type === 'color' && topCategory === 'color') {
    return `  --color-${sanitize(key)}: ${colorValue(token.$value)};`
  }

  if (token.$type === 'number' && topCategory === 'spacing') {
    return `  --space-${token.$value}: ${token.$value}px;`
  }

  if (token.$type === 'string' && topCategory === 'font-family') {
    const name = sanitize(key.replace(/^font-family-/, ''))
    return `  --font-${name}: '${token.$value}', sans-serif;`
  }

  warnings.push(
    `Skipped "${path.join('.')}" — type "${token.$type}" doesn't match its category "${topCategory}". Value: ${JSON.stringify(token.$value)}`
  )
  return null
}

function walk(node, topCategory, path) {
  const lines = []

  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue
    const nextPath = [...path, key]

    if (value && typeof value === 'object' && '$type' in value) {
      const line = buildLine(key, value, topCategory, nextPath)
      if (line) lines.push(line)
    } else if (value && typeof value === 'object') {
      lines.push(...walk(value, topCategory, nextPath))
    }
  }

  return lines
}

// Catches names that look like an accidental duplicate from Figma
// (e.g. "red-900 2", which usually means someone created a variable
// with a name that already existed and Figma appended " 2").
function checkForSuspiciousNames(node, path) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue

    if (/\s\d+$/.test(key)) {
      warnings.push(
        `"${[...path, key].join('.')}" looks like an accidental duplicate from Figma (name ends in " <number>"). Worth checking/renaming at the source.`
      )
    }

    if (value && typeof value === 'object' && !('$type' in value)) {
      checkForSuspiciousNames(value, [...path, key])
    }
  }
}

const raw = JSON.parse(readFileSync(INPUT_PATH, 'utf-8'))
const lines = []

for (const [category, value] of Object.entries(raw)) {
  if (category.startsWith('$')) continue
  lines.push(`  /* ${category} */`)
  lines.push(...walk(value, category, [category]))
  lines.push('')
}

checkForSuspiciousNames(raw, [])

const output = `/* AUTO-GENERATED by scripts/build-tokens.js — do not edit by hand.
   Source: design-tokens/primitives.json
   Regenerate with: npm run tokens */

:root {
${lines.join('\n')}
}
`

mkdirSync(dirname(OUTPUT_PATH), { recursive: true })
writeFileSync(OUTPUT_PATH, output)

console.log(`Wrote ${OUTPUT_PATH}`)
if (warnings.length) {
  console.log('\nWarnings:')
  warnings.forEach((w) => console.log(' - ' + w))
}
